# newsyslog config for Mabure's logs.
# logfilename                        [owner:group]  mode  count  size(KB) when  flags
/Library/Logs/Mabure/events.full.jsonl   root:wheel  600    10     10240   *     J
/Library/Logs/Mabure/events.jsonl        root:wheel  644    10     10240   *     J
/var/log/mabure/daemon.out.log           root:wheel  644    5      10240   *     J
/var/log/mabure/daemon.err.log           root:wheel  644    5      10240   *     J
